"""update model

Revision ID: 74a7d7d45174
Revises: 7f95a42ba9d5
Create Date: 2025-05-25 21:57:26.341353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a7d7d45174'
down_revision = '7f95a42ba9d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('provider_id', sa.Integer(), nullable=False))
        batch_op.alter_column('diagnosis',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'providers', ['provider_id'], ['id'])
        batch_op.create_foreign_key(None, 'patients', ['patient_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('diagnosis',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('provider_id')
        batch_op.drop_column('patient_id')

    # ### end Alembic commands ###
