"""update patient

Revision ID: 7f95a42ba9d5
Revises: f4fb02a28f9e
Create Date: 2025-05-25 18:06:21.743398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f95a42ba9d5'
down_revision = 'f4fb02a28f9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_number', sa.String(length=20), nullable=True))
        batch_op.drop_constraint(batch_op.f('patients_national_id_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['patient_number'])
        batch_op.drop_column('address')
        batch_op.drop_column('national_id')

    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('national_id', sa.String(length=30), nullable=True))
        batch_op.create_unique_constraint(None, ['national_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('national_id')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('national_id', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('patients_national_id_key'), ['national_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('patient_number')

    # ### end Alembic commands ###
