"""update model appointment

Revision ID: ad2b105d90b8
Revises: de539aa06191
Create Date: 2025-05-26 17:11:23.408295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad2b105d90b8'
down_revision = 'de539aa06191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rescheduled_start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rescheduled_end_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('rescheduled_end_time')
        batch_op.drop_column('rescheduled_start_time')

    # ### end Alembic commands ###
