"""update user model

Revision ID: e750576597e4
Revises: f5976cae4fcb
Create Date: 2025-05-25 15:30:27.612311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e750576597e4'
down_revision = 'f5976cae4fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('users_provider_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'persons', ['person_id'], ['id'])
        batch_op.drop_column('provider_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('users_provider_id_fkey'), 'providers', ['provider_id'], ['id'])
        batch_op.drop_column('person_id')

    # ### end Alembic commands ###
